# Conversion to YAML from Properties formar report
# Warnings:
# - The yaml file had comments which are lost in the refactoring!
spring:
  application:
    name: PRODUCT-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/product_live_demo
    username: root
    password: Arjunjr@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  cloud:
    config:
      enabled: false
server:
  port: 8080
eureka:
  client:
    enabled: false
